### ISSUE TITLE
Set default language?

### ISSUE THREAD

**Issue by HerrBertling** [jGleitz/markdown-it-prism#12]
Hey :)

I'm probably missing something simple here: How would I set a default or fallback language to be passed if the used language is not detected or supported?

I've got some code blocks in markdown that either don't have a specific language defined or that have `vue` defined. I'd like to fall back to `javascript` for both cases.

**Comment by jGleitz** [comment]
Hi! 

I haven’t thought of such use cases before, but I think it would make sense for this plugin to support it.

I have implemented a solution in #14. Can you please check whether:

 1. You find the options easy to understand and appropriately named
 1. They cover the use case you have in mind

**Comment by HerrBertling** [comment]
That's awesome, thank you so much for the effort 👍
