### ISSUE TITLE
Clarify license terms - what is a derived work?

### ISSUE THREAD

**Issue by MikeRalphson** [jGleitz/markdown-it-prism#250]
This project is GPL3 licensed. With a strict reading of that license, code that is linked must also be released under a GPL3-compatible license.

Can you clarify what is a "derived work" when code uses (links to) this software?

Would you consider re-licensing under the LGPL?

I ask because this code is the only GPL-licensed code in a project we are building.

**Comment by jGleitz** [comment]
Thank you for your request! I see no good reason to have this project under a GPL-like license, so I re-licensed it under MIT, which I use for most of my works anyway. I hope you can make good use of this little project!

**Comment by jGleitz** [comment]
v2.1.5 was released under the MIT licence (the npm web page has not yet picked that up, though).

**Comment by MikeRalphson** [comment]
Thank you!

**Comment by MikeRalphson** [comment]
Ah, npm won't have picked this up as package.json still says GPL-3.0 ;)

**Comment by jGleitz** [comment]
:facepalm:.

fixed in v2.1.6. Thank you for the pointer!
