### ISSUE TITLE
v2.0.4 should be a new major release

### ISSUE THREAD

**Issue by DanielFGray** [jGleitz/markdown-it-prism#48]
v2.0.4 seems to bump compatibility from node LTS version 12.x to 13.x

I believe this should constitute bump in major semver since it's a breaking change requiring to install a new node version

**Comment by nathancahill** [comment]
@jGleitz I think this commit did not make it in to the version published on npm: https://github.com/jGleitz/markdown-it-prism/commit/66a623943605854e5d128cdd64100abc5c8a9890

The version on npm has:

```js
"engines": {
    "node": "13.8.0"
}
```

Should be as simple as bumping to 2.0.5 and republishing.

**Comment by jGleitz** [comment]
Ah, my bad. @nathancahill, you are right, the `engine` change should not have been published. I have not yet learned how to keep renovate from updating the `engine`.

**Comment by jGleitz** [comment]
`v2.0.5` has node `>=10.0.0` again. Thank you for reporting this and sorry for the inconvenience!
