### ISSUE TITLE
hope to add types for typescript.

### ISSUE THREAD

**Issue by Innei** [jGleitz/markdown-it-prism#59]
![image](https://user-images.githubusercontent.com/41265413/78967121-1dff2e00-7b34-11ea-9efe-f76625154e9f.png)

**Comment by jGleitz** [comment]
Hi! I agree that adding typings for typescript would be a good idea for this project!

I cannot promise when I will get to it, though. I would, however, gladly accept a pull request that adds types or, even better, converts the whole project to Typescript.

**Comment by Innei** [comment]
Hi, I just made a sample but it's interfaces isn't completed.
```ts
declare module 'markdown-it-prism' {
  import MarkdownIt from 'markdown-it'
  export interface MarkdownItPrismOptions {
    plugins?: string[]
    init?: any
    defaultLanguageForUnknown?: string
    defaultLanguageForUnspecified?: string
    defaultLanguage?: string
  }
  export default function markdownItPrism(
    markdownit: MarkdownIt,
    useroptions?: MarkdownItPrismOptions,
  ): void
}
```

**Comment by jGleitz** [comment]
Hi! Even though I have been silent on this (I have not been doing any Open Source work at all in the past weeks), I still want to have type information for this project. So I will keep this ticket open.

**Comment by jGleitz** [comment]
I converted this project into a Typescript project and published its types. @Innei, does that help you?
