### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by zhaokuohaha** [jGleitz/markdown-it-prism#6]
Hi, I want to use this plugin in  my code , but it seems not work, my code : 

```js
const prism = require('markdown-it-prism')
var md = require('markdown-it')({
  html: true,
  linkify: true,
}).use(prism)

....

```

and I use `md.render(text)` to insert into `span` as innerHTML

but it doesn't hightlight,  is that something I doesn't do ?

**Comment by jGleitz** [comment]
Hi @zhaokuohaha ! 

From what I can tell from your code snippet, you’re using `markdown-it-prism` correctly. Please be aware that the plugin will only add markup to the output HTML (i.e. `<span>`s around keywords etc.) but will not include a stylesheet that makes the markup look any different.

To make the output of `markdown-it-prism` actually highlighted, you have to include a stylesheet into your html page. This is explained in PrismJS’ [basic usage](http://prismjs.com/#basic-usage).

Does that help you?

**Comment by jGleitz** [comment]
I have added a note about including a stylesheet to the README

**Comment by zhaokuohaha** [comment]
Got it!!  Thank you ! :kissing_heart:

**Comment by jGleitz** [comment]
I’m glad to hear that!
