### ISSUE TITLE
The package is not consistent with the npmjs website

### ISSUE THREAD

**Issue by CareyQ** [jGleitz/markdown-it-prism#683]
Can it be republished to npmjs.

npmjs:
![image](https://user-images.githubusercontent.com/31696069/206232702-9ab025e4-72b1-4270-82a2-4eefdd366f18.png)

here:
![image](https://user-images.githubusercontent.com/31696069/206232920-e9850bc3-7a79-49f2-b595-b341df8b8760.png)

**Comment by jGleitz** [comment]
Hi, thank you for your report!

Every relevant change to this repository's code is automatically published to npm by [semantic-release](https://github.com/semantic-release/semantic-release).

However, this project uses TypeScript, which is compiled down to plain JavaScript before publishing. The npm page shows the contents of the package, which is the compiled JavaScript. That is why you see a difference.

If you check out this repository and run `npm build`, you will find the compiled code in the `build` directory. This will match what you see on the NPM page.

I hope this helps!
